apiVersion: v1
kind: Secret
metadata:
  name: gcr-service-account-jhub-42b5pz2e
  namespace: hyperplane-development
data:
  gcr-hyperplane-credentials.json: <TOREPLACE_HYPERPLANE_SERVICE_ACCOUNT_JSON>
