apiVersion: v1
kind: Service
metadata:
  labels:
    app: git-server
  name: git-server
  namespace: hyperplane-workloads
spec:
  ports:
  - port: 22
    protocol: TCP
  selector:
    app: git-server
  type: ClusterIP
