apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hyperplanepodspecs.crds.hyperplane.com
spec:
  group: crds.hyperplane.com
  names:
    kind: HyperplanePodSpec
    listKind: HyperplanePodSpecList
    plural: hyperplanepodspecs
    singular: hyperplanepodspec
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              displayName:
                type: string
              description:
                type: string
              icon: 
                type: string
              imageUrl:
                type: string
              volumeMounts:
                type: array
                items:
                  type: object
                  properties:
                    mountPath:
                      type: string
                    mountPropagation:
                      type: string
                    name:
                      type: string
                    readOnly:
                      type: boolean
                    subPath:
                      type: string
                    subPathExpr:
                      type: string
              volumes:
                type: array
                x-kubernetes-preserve-unknown-fields: true
                items:
                  type: object
                  properties:
                    name: 
                      type: string
                    cephfs:
                      properties:
                        monitors:
                          items:
                            type: string
                          type: array
                        path:
                          type: string
                        readOnly:
                          type: boolean
                        secretFile:
                          type: string
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                        user:
                          type: string
                      type: object
                    configMap:
                      properties:
                        defaultMode:
                          format: int32,
                          type: integer
                        items:
                          items:
                            properties:
                              key:
                                type: string
                              mode:
                                format: int32,
                                type: integer
                              path:
                                type: string
                            required:
                              - key
                              - path
                            type: object
                          type: array
                        name:
                          type: string
                        optional:
                          type: boolean
                      type: object
                    emptyDir:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    persistentVolumeClaim:
                      type: object
                      properties:
                        claimName:
                          type: string
              resources:
                type: object
                properties:
                  num_gpus:
                    type: integer
                    minimum: 0
                    default: 0
                  limits:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    properties:
                      memory:
                        type: string
                      cpu:
                        type: string
                  requests:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    properties:
                      memory:
                        type: string
                      cpu:
                        type: string
              env:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    value: 
                      type: string
              envar:
                type: object
                properties:
                  name: 
                    type: string
                  value: 
                    type: string
                  valueFrom:
                    type: object
                    properties:
                      configMapKeyRef:
                        type: object
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                          optional:
                            type: boolean
                      fieldRef:
                        type: object
                        properties:
                          apiVersion:
                            type: string
                          fieldPath:
                            type: string
                      secretKeyRef:
                        type: object
                        properties:
                          key:
                            type: string
                          value:
                            type: string
                          optional:
                            type: boolean
              nodeSelectorKey:
                type: string
              nodeSelectorValue:
                type: string
              imagePullPolicy: 
                type: string
                enum:
                - Always
                - IfNotPresent
                - Never
              workingDir:
                type: string
              nodeSelector:
                x-kubernetes-preserve-unknown-fields: true
                type: object
                properties:
                  <TOREPLACE_NODE_SELECTOR_EXPRESSIONS_KEY>:
                    type: string
                  dask: 
                    type: string
                  ray: 
                    type: string
                  nodegroup: 
                    type: string
                  hyperplane.dev/nodeType:
                    type: string
                  cloud.google.com/gke-nodepool: 
                    type: string
    served: true
    storage: true
    subresources:
      status: {}
      