pipeline:
  name: "Example pipeline that runs all tasks in parallel"
  tasks:
  - name: "step1"
    type: "jupyter notebook"
    notebook_path: "fake_pipeline/step1.ipynb"
    notebook_output_path: "step1_output.ipynb"
    depends_on: []
  - name: "step2"
    type: "jupyter notebook"
    notebook_path: "fake_pipeline/step2.ipynb"
    notebook_output_path: "step2_output.ipynb"
    depends_on: []
  - name: "step3"
    type: "jupyter notebook"
    notebook_path: "fake_pipeline/step3.ipynb"
    notebook_output_path: "step3_output.ipynb"
    depends_on: []
  - name: "step4"
    type: "jupyter notebook"
    notebook_path: "fake_pipeline/step4.ipynb"
    notebook_output_path: "step4_output.ipynb"
    depends_on: []
  - name: "step5"
    type: "jupyter notebook"
    notebook_path: "fake_pipeline/step5.ipynb"
    notebook_output_path: "step5_output.ipynb"
    depends_on: []