apiVersion: v1
kind: Secret
metadata:
  name: service-account-key-certmanager-y7pshm5k
  namespace: hyperplane-certmanager
data:
  <TOREPLACE_DNS_SERVICEACCOUNT_KEYFILE_NAME>: <TOREPLACE_DNS_SERVICEACCOUNT_KEYFILE_CONTENTS>
