apiVersion: v1
kind: Secret
metadata:
  name: gcr-service-account-key-pipelines-zsaw8epg
  namespace: hyperplane-workloads
data:
  gcr-hyperplane-credentials.json: <TOREPLACE_HYPERPLANE_SERVICE_ACCOUNT_JSON>
