apiVersion: v1
data:
  id_rsa: <TOREPLACE_ID_RSA>
  id_rsa.pub: <TOREPLACE_ID_RSA_PUB>
  known_hosts: <TOREPLACE_KNOWN_HOSTS>
kind: Secret
metadata:
  name: github-deploy-key-ancrht4u
  namespace: hyperplane-workloads
type: Opaque
