pipeline:
  name: "Getting Started Pipeline"
  job_type: "gpu"  
  tasks:
  - name: "RAPIDs Notebook"
    type: "jupyter notebook"
    notebook_path: "example_notebooks/pipelines/rapids_pipeline/rapids_data_processing.ipynb"
    notebook_output_path: "rapids_data_processing_output.ipynb"