apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipelines-role-core-cwxtsd6t
  namespace: hyperplane-workloads
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  - endpoints
  - persistentvolumeclaims
  - pods/log
  - events
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - extensions
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - crds.hyperplane.com
  resources:
  - hyperplanepodspecs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - keda.sh
  resources:
  - scaledjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups: 
  - ""
  resources:
  - serviceaccounts
  - secrets
  verbs:
  - create
  - list
  - delete
  - get
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - list
  - delete
  - get
# may be needed for keyvault if use-case is later expanded
#- apiGroups:
#  - secrets-store.csi.x-k8s.io
#  resources:
#  - secretproviderclasses
#  - secretproviderclasspodstatuses
#  verbs:
#  - get
#  - list
#  - watch
#- apiGroups:
#  - storage.k8s.io
#  resources:
#  - csidrivers
#  verbs:
#  - get
#  - list
#  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipelines-role-binding-core-11o0onty
  namespace: hyperplane-workloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipelines-role-core-cwxtsd6t
subjects:
- kind: ServiceAccount
  name: hyperplane-operator
  namespace: <TOREPLACE_RELEASE_NAMESPACE>