apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-pipeline-role-binding-jqrypvlh
  namespace: hyperplane-workloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipelines-role-cwxtsd6t
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: <TOREPLACE_RELEASE_NAMESPACE>
